### ISSUE TITLE
Center option

### ISSUE THREAD

**Issue by brunomonteiro3** [Gajotres/IonicCarouselDemo#1]
Hello,

First of all, great tool. Many thanks for making it open-source!

Is there any way to set the current slide on the "center" of the page? 

Owl Carousel has the option I'm trying to reproduce:
http://www.owlcarousel.owlgraphic.com/demos/center.html

And it's also possible to use the slider without using ng-repeat?

Thanks!

**Comment by Gajotres** [comment]
Hi,

yes you can do that, just read official carousel documentation.

http://www.idangero.us/swiper/demos/#.ViSi9_mqpBc and look for a title
called *Centered Slides.*

Kind Regards,
Gajotres

2015-10-16 17:31 GMT+02:00 Bruno Monteiro <notifications@github.com>:

**Comment by Gajotres** [comment]
Hi,

yes you can do that, just read the official carousel documentation.

http://www.idangero.us/swiper/demos/#.ViSi9_mqpBc and look for a title called Centered Slides.

Kind Regards,
Gajotres

**Comment by brunomonteiro3** [comment]
Thanks! :) Problem solved.
